.PHONY: core-gpu-deps
core-gpu-deps:
	buildah unshare ./core-gpu-deps.sh

.PHONY: core-gpu-gcc-15.2.0-cuda-13.1.1
core-gpu-gcc-15.2.0-cuda-13.1.1:
	buildah unshare ./core-gpu-gcc-15.2.0-cuda-13.1.1.sh
