#!/bin/bash

echo 'Launching RStudio Server...'

# Disable hardware acceleration
XDG_RUNTIME_DIR=""

# Define TMPDIR
export TMPDIR=/tmp

# Get RSTUDIO_PASSWORD
export RSTUDIO_PASSWORD=$(openssl rand -base64 15)

# Get RSTUDIO_UUID
export RSTUDIO_UUID=$(uuidgen)
echo $RSTUDIO_UUID > $TMPDIR/${USER}_secure-cookie-key

# TMPDIR settings
if test -f ~/.Renviron; then
    sed -i '/TMPDIR/d' ~/.Renviron
    sed -i '/OMP_NUM_THREADS/d' ~/.Renviron
fi

echo "TMPDIR=$TMPDIR" >> ~/.Renviron

mkdir -p "$TMPDIR/var/lib"
mkdir -p "$TMPDIR/var/run"

# Start RStudio Server
PASSWORD=$RSTUDIO_PASSWORD \
RSTUDIO_SESSION_TIMEOUT='0' \
singularity exec \
-B $TMPDIR:$TMPDIR \
-B $TMPDIR/var/lib:/var/lib/rstudio-server \
-B $TMPDIR/var/run:/var/run/rstudio-server \
-B /opt/r-env-singularity/4.0.5/4.0.5-rpackages:/opt/r-env-singularity/4.0.5/4.0.5-rpackages \
/opt/r-env-singularity/4.0.5/4.0.5-sdd.sif rserver \
--auth-none=0 \
--server-data-dir "$TMPDIR/${USER}" \
--secure-cookie-key-file $TMPDIR/${USER}_secure-cookie-key \
--auth-pam-helper-path=pam-helper & pid=$!

# write out launch instructions
echo -e "
    RStudio Server - Sensitive Data Desktop Edition
    -------------------------------------------------
    Copy/Paste this URL into a browser:
    http://localhost:8787/
    -------------------------------------------------
    Enter these at the RStudio Server sign-in screen
    Username: $USER Password: $RSTUDIO_PASSWORD
    -------------------------------------------------
    To stop RStudio Server: Ctrl + C
    "

# Trap CTRL-C and wait for the server
trap "kill -1 $pid" SIGINT
wait $pid

